# Generated by Django 4.2.8 on 2023-12-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Stops',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Waiting', 'Waiting'), ('Start', 'Start'), ('On The Way', 'On The Way'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Waiting', max_length=30)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bus_stop_id', related_query_name='stop_id', to='users.bus_details')),
            ],
            options={
                'db_table': 'bus_stops',
            },
        ),
    ]
